name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 触发条件：推送以 'v' 开头的标签，例如 v1.0.0

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android Release APK
        run: ./gradlew :composeApp:assembleRelease

      - name: Sign Android APK
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: composeApp/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{steps.sign_app.outputs.signedFile}}

  build-desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            task: packageDeb
            artifact-name: linux-deb
            artifact-path: composeApp/build/compose/binaries/main/deb/*.deb
          - os: macos-latest
            task: packageDmg
            artifact-name: macos-dmg
            artifact-path: composeApp/build/compose/binaries/main/dmg/*.dmg
          - os: windows-latest
            task: packageMsi
            artifact-name: windows-msi
            artifact-path: composeApp/build/compose/binaries/main/msi/*.msi

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build Desktop Package (Unix)
        if: runner.os != 'Windows'
        run: ./gradlew :composeApp:${{ matrix.task }}

      - name: Build Desktop Package (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat :composeApp:${{ matrix.task }}

      - name: Upload Desktop Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}

  create-release:
    needs: [build-android, build-desktop]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/android-apk/*.apk
            artifacts/linux-deb/*.deb
            artifacts/macos-dmg/*.dmg
            artifacts/windows-msi/*.msi
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
